/* NFRAMEWORK */var aa75e46b2_5925_43c9_9bd6_c23e94166c34_module;manager=window.NFramework.nmoduleManager,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.my_mb=!0;class my_mb_class extends HTMLElement{constructor(){super(),this.componentName="my-mb"}render(){let e=document.createElement("style");return e.textContent=`

            my-button{
                color: red;
            }

        `,this.appendChild(e),[(()=>{var e=document.createElement("h1");if(e.innerHTML+="\r\n\r\n                    my-mb\r\n\r\n                ",null!=e.render){var n=e.render();if(null!=n)for(var r of n)e.appendChild(r)}return e})()]}}customElements.define("my-mb",my_mb_class),null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.my_button=!0;class my_button_class extends HTMLElement{constructor(){super(),this.componentName="my-button"}render(){let e=document.createElement("style");return e.textContent=`

            my-button{
                color: blue;
            }

        `,this.appendChild(e),[(()=>{if(null!=window.NFramework.customTags.ui&&null!=window.NFramework.customTags.ui.my_mb)return(()=>{var e=document.createElement("my-mb");if(e.innerHTML+="\r\n\r\n                    OK\r\n\r\n                ",null!=e.render){var n=e.render();if(null!=n)for(var r of n)e.appendChild(r)}return e})()})()]}}customElements.define("my-button",my_button_class),null==window.NFramework.nmoduleManager.nlcElementRunned["0e86c670_c4ae_4e96_9962_e71cd7674941"]&&(window.NFramework.nmoduleManager.nlcElementRunned["0e86c670_c4ae_4e96_9962_e71cd7674941"]=!0,(()=>{var n=new window.NFramework.NModule;n.side="both",n.name="demo",n.__TYPE="NMODULE",n.RunExternalMethod=function(e){e.call(n)},n.RunExternalMethod(function(){this.AddProperty("prop"),this.AddMethod("setup",async(...e)=>{let n=async function(){this.GetThisWithCallback(e=>{aa75e46b2_5925_43c9_9bd6_c23e94166c34_module=e});let e={set stter(e){aa75e46b2_5925_43c9_9bd6_c23e94166c34_module.Set("prop",e)}};e.stter='console.log("clicked");',manager.Get("dom").GetThisWithCallback(e=>e.Get("body")).appendChild((()=>{if(null!=window.NFramework.customTags.ui&&null!=window.NFramework.customTags.ui.my_button)return(()=>{var e=document.createElement("my-button");if(e.innerHTML+="\r\n\r\n                    ",null!=e.render){var n=e.render();if(null!=n)for(var r of n)e.appendChild(r)}return e})()})())}.bind(this);return n(...e)})}),window.NFramework.nmoduleManager.ImportModule(n)})());