/* NFRAMEWORK */manager=window.NFramework.nmoduleManager,null==window.NFramework.nmoduleManager.nlcElementRunned["4848cb73_f33d_4145_ae87_a9d967a8edd3"]&&(window.NFramework.nmoduleManager.nlcElementRunned["4848cb73_f33d_4145_ae87_a9d967a8edd3"]=!0,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.demo_main_ui=!0,(()=>{var r=window.NFramework.uiManager;function e(e){return r.uiComponentClasses[e]}r.uiComponentClassCreators.push({classCreator:()=>{class n extends r.uiComponentClasses.UIComponent{constructor(){super()}render(){return this.setAttribute("class","mainUICClass"),[`

                `,(()=>{var e,n;if(null!=window.NFramework.customTags.ui&&null!=window.NFramework.customTags.ui.demo_ui)return(n=document.createElement("demo-ui")).setAttribute("NUI_id","1af2917b_bc00_4c67_9229_cfe0dd88bb04"),n.callInside=function(){n.innerHTML+=`

                `},n.callInside.call(n),null!=n.render&&(n.render instanceof(async()=>{}).constructor?(async()=>{var e=await n.render();null!=e&&n.AppendChilds(e)})():null!=(e=n.render())&&n.AppendChilds(e)),n})(),`

            `]}}return n.prototype.componentName="demo-main-ui",n.prototype.UIClass=e,n.render=function(e){let o=[];return null!=n.prototype.render&&(o=n.prototype.render.call(e)),o.add=function(e){for(var n of e)o.push(n);return o},o.addBefore=function(e){let n=e;for(var r of o)n.push(r);return n},o},r.mainUIComponentClass=n,r.mainUIComponentName="demo-main-ui",r.mainComponentNUI_id="b2a404f4_642b_4a37_9286_a37c417a516f",n},extends:"UIComponent",name:"demo-main-ui"})})()),null==window.NFramework.nmoduleManager.nlcElementRunned.bb7bfd56_ef1c_4e45_a11c_f1dee95c9d2f&&(window.NFramework.nmoduleManager.nlcElementRunned.bb7bfd56_ef1c_4e45_a11c_f1dee95c9d2f=!0,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.demo_ui=!0,(()=>{var r=window.NFramework.uiManager;function e(e){return r.uiComponentClasses[e]}r.uiComponentClassCreators.push({classCreator:()=>{class n extends r.uiComponentClasses["demo-ui-base"]{constructor(){super()}render(){return e("demo-ui-base").render(this).add([`     
                    Hello
                `])}}return n.prototype.componentName="demo-ui",n.prototype.UIClass=e,n.render=function(e){let o=[];return null!=n.prototype.render&&(o=n.prototype.render.call(e)),o.add=function(e){for(var n of e)o.push(n);return o},o.addBefore=function(e){let n=e;for(var r of o)n.push(r);return n},o},n},extends:"demo-ui-base",name:"demo-ui"})})()),null==window.NFramework.nmoduleManager.nlcElementRunned["24ec38b8_379e_49f8_94a9_208356ac4ef2"]&&(window.NFramework.nmoduleManager.nlcElementRunned["24ec38b8_379e_49f8_94a9_208356ac4ef2"]=!0,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.demo_ui_base=!0,(()=>{var r=window.NFramework.uiManager;function e(e){return r.uiComponentClasses[e]}r.uiComponentClassCreators.push({classCreator:()=>{class n extends r.uiComponentClasses.UIComponent{constructor(){super()}render(){return[`        
                Hello World Base
            `]}}return n.prototype.componentName="demo-ui-base",n.prototype.UIClass=e,n.render=function(e){let o=[];return null!=n.prototype.render&&(o=n.prototype.render.call(e)),o.add=function(e){for(var n of e)o.push(n);return o},o.addBefore=function(e){let n=e;for(var r of o)n.push(r);return n},o},n},extends:"UIComponent",name:"demo-ui-base"})})());