/* NFRAMEWORK */(()=>{var r,o,a;function t(e){return r.uiComponentClasses[e]}function u(e){return o.uiComponentClasses[e]}function s(e){return a.uiComponentClasses[e]}manager=window.NFramework.nmoduleManager,null==window.NFramework.nmoduleManager.nlcElementRunned["4f98992d_c237_4ea8_9c3e_91b1365b70ac"]&&(window.NFramework.nmoduleManager.nlcElementRunned["4f98992d_c237_4ea8_9c3e_91b1365b70ac"]=!0,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.demo_main_ui=!0,(r=window.NFramework.uiManager).uiComponentClassCreators.push({classCreator:()=>{var e=(()=>{try{return"UIComponent"}catch{return'"UIComponent"'}})();class n extends r.uiComponentClasses[e]{constructor(){super()}render(){return[`

                `,(()=>{var e,n;if(null!=window.NFramework.customTags.ui&&null!=window.NFramework.customTags.ui.demo_ui)return(n=document.createElement("demo-ui")).setAttribute("NUI_id","59015ab1_948e_4e6a_ba19_c8914c81fa52"),n.callInside=function(){n.innerHTML+=`

                `},n.callInside.call(n),null!=n.render&&(n.render instanceof(async()=>{}).constructor?(async()=>{var e=await n.render();null!=e&&n.AppendChilds(e)})():null!=(e=n.render())&&n.AppendChilds(e)),n})(),`

            `]}}return n.prototype.componentName="demo-main-ui",n.prototype.UIClass=t,n.render=function(e){let o=[];return null!=n.prototype.render&&(o=n.prototype.render.call(e)),o.add=function(e){for(var n of e)o.push(n);return o},o.addBefore=function(e){let n=e;for(var r of o)n.push(r);return n},o},r.mainUIComponentClass=n,r.mainUIComponentName="demo-main-ui",r.mainComponentNUI_id="78013c36_fd42_45a8_b3c4_6f902e156af7",n},extends:"UIComponent",name:"demo-main-ui"})),null==window.NFramework.nmoduleManager.nlcElementRunned.d2ff97ca_ab8e_4aaf_8c7f_e1d52feea0af&&(window.NFramework.nmoduleManager.nlcElementRunned.d2ff97ca_ab8e_4aaf_8c7f_e1d52feea0af=!0,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.demo_ui=!0,(o=window.NFramework.uiManager).uiComponentClassCreators.push({classCreator:()=>{var e=(()=>{try{return"demo-ui-base"}catch{return"'demo-ui-base'"}})();class n extends o.uiComponentClasses[e]{constructor(){super()}render(){return u("demo-ui-base").render(this).add([`     
                    Hello
                `])}}return n.prototype.componentName="demo-ui",n.prototype.UIClass=u,n.render=function(e){let o=[];return null!=n.prototype.render&&(o=n.prototype.render.call(e)),o.add=function(e){for(var n of e)o.push(n);return o},o.addBefore=function(e){let n=e;for(var r of o)n.push(r);return n},o},n},extends:"demo-ui-base",name:"demo-ui"})),null==window.NFramework.nmoduleManager.nlcElementRunned["82b5eb32_18b1_4744_b02f_0ef720f0806e"]&&(window.NFramework.nmoduleManager.nlcElementRunned["82b5eb32_18b1_4744_b02f_0ef720f0806e"]=!0,null==window.NFramework.customTags.ui&&(window.NFramework.customTags.ui=new Object),window.NFramework.customTags.ui.demo_ui_base=!0,(a=window.NFramework.uiManager).uiComponentClassCreators.push({classCreator:()=>{var e=(()=>{try{return"UIComponent"}catch{return'"UIComponent"'}})();class n extends a.uiComponentClasses[e]{constructor(){super()}render(){return[`        
                Hello World Base
            `]}}return n.prototype.componentName="demo-ui-base",n.prototype.UIClass=s,n.render=function(e){let o=[];return null!=n.prototype.render&&(o=n.prototype.render.call(e)),o.add=function(e){for(var n of e)o.push(n);return o},o.addBefore=function(e){let n=e;for(var r of o)n.push(r);return n},o},n},extends:"UIComponent",name:"demo-ui-base"}))})();